[package]
name = "linkerd-access-log"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
base64 = "0.13"
chrono = "0.4.15"
futures = "0.3"
http = "0.2"
pin-project = "1"
linkerd-stack = { path = "../stack" }
linkerd-identity = { path = "../identity" }
linkerd-proxy-transport = { path = "../proxy/transport" }
tracing = "0.1.19"
tracing-subscriber = "0.2.12"
