name: Kubernetes

on:
  pull_request: {}
  push:
    branches:
      - "ver/k3d-tests"

jobs:
  k3d-test:
    name: K3d Tests
    permissions:
      contents: read
    timeout-minutes: 20
    runs-on: ubuntu-latest

    env:
      DOCKER_UNOPTIMIZED: "1"
      LINKERD_VERSION: edge-21.5.2
      K3D_VERSION: v4.4.4
      KUBECTL_VERSION: v1.21.1
      PROXY_IMAGE: linkerd-ci/linkerd/proxy

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Install tools
        run: |
          mkdir -p ./target/bin
          cd ./target/bin
          curl -vsLo kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod 755 kubectl
          curl -vsLo k3d "https://github.com/rancher/k3d/releases/download/${K3D_VERSION}/k3d-linux-amd64"
          chmod 755 k3d
          curl -vsLo linkerd "https://github.com/linkerd/linkerd2/releases/download/${LINKERD_VERSION}/linkerd2-cli-${LINKERD_VERSION}-linux-amd64"
          chmod 755 linkerd

      - name: Create cluster
        run: ./target/bin/k3d cluster create

      - name: Load Linkerd images
        run: |
          docker pull ghcr.io/linkerd/controller:${LINKERD_VERSION} &
          docker pull ghcr.io/linkerd/proxy:${LINKERD_VERSION} &
          docker pull ghcr.io/linkerd/proxy-init:${LINKERD_VERSION} &
          wait %1 %2 %3
          ./target/bin/k3d image import \
              ghcr.io/linkerd/controller:${LINKERD_VERSION} \
              ghcr.io/linkerd/proxy:${LINKERD_VERSION} \
              ghcr.io/linkerd/proxy-init:${LINKERD_VERSION}

      - name: Install Linkerd in cluster
        run: |
          ./target/bin/linkerd check --pre

          ./target/bin/linkerd install \
                --set controllerImage=ghcr.io/linkerd/controller \
                --set proxyImage=ghcr.io/linkerd/proxy \
                --set proxyInitImage=ghcr.io/linkerd/proxy-init \
              | ./target/bin/kubectl apply -f -

          for i in $(seq 1 10); do
            if ./target/bin/linkerd check --wait=1m; then
              exit 0
            fi
            ./target/bin/kubectl get po -n linkerd
          done
          ./target/bin/kubectl get po -o yaml -n linkerd | grep -F 'image:'

      # Build a docker image for the working proxy, based on a recent Linkerd version for its
      # runtime image.
      - name: Build proxy
        run: |
          RUNTIME_IMAGE=ghcr.io/linkerd/proxy:${LINKERD_VERSION} DOCKER_TAG=${PROXY_IMAGE}:${GITHUB_SHA} make docker
          ./target/bin/k3d image import ${PROXY_IMAGE}:${GITHUB_SHA}

      - name: Run tests
        run: |
          ./target/bin/kubectl get po -A
          exit 1 # TODO
