name: Kubernetes

on:
  pull_request: {}
  push:
    branches:
      - "ver/k3d-tests"

jobs:
  k3d-test:
    name: K3d Tests
    permissions:
      contents: read
    timeout-minutes: 20
    runs-on: ubuntu-latest

    env:
      DOCKER_UNOPTIMIZED: "1"
      LINKERD_VERSION: edge-21.5.2
      K3D_VERSION: v4.4.4
      KUBECTL_VERSION: v1.21.1
      PROXY_IMAGE: linkerd-ci/linkerd/proxy

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Install tools
        run: |
          mkdir -p ./target/bin
          curl -vsLo ./target/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod 755 ./target/bin/kubectl
          curl -vsLo ./target/bin/k3d "https://github.com/rancher/k3d/releases/download/${K3D_VERSION}/k3d-linux-amd64"
          chmod 755 ./target/bin/k3d
          curl -vsLo ./target/bin/linkerd "https://github.com/linkerd/linkerd2/releases/download/${LINKERD_VERSION}/linkerd2-cli-${LINKERD_VERSION}-linux-amd64"
          chmod 755 ./target/bin/linkerd

      # Build a docker image for the working proxy, based on a recent Linkerd version for its
      # runtime image.
      - name: Docker
        run: RUNTIME_IMAGE=ghcr.io/linkerd/proxy:${LINKERD_VERSION} DOCKER_TAG=${PROXY_IMAGE}:${GITHUB_SHA} make docker

      - name: Setup cluster
        run: |
          ./target/bin/k3d cluster create
          ./target/bin/k3d image import ${PROXY_IMAGE}:${GITHUB_SHA}

      - name: Instal Linkerd in cluster
        run: |
          ./target/bin/linkerd check --pre

          ./target/bin/linkerd install \
                --set controllerImage=ghcr.io/linkerd/controller \
                --set proxyImage=ghcr.io/linkerd/proxy \
                --set proxyInitImage=ghcr.io/linkerd/proxy-init \
              | ./target/bin/kubectl apply -f -

          for i in $(seq 1 9); do
            ./target/bin/linkerd check --wait=1m || ./target/bin/kubectl get po - linkerd
          done
          ./target/bin/linkerd check --wait=1m


      - name: Run tests
        run: |
          ./target/bin/kubectl get po -A
          # TODO
