name: Kubernetes

on:
  pull_request: {}
  push:
    branches:
      - "ver/k3d-tests"

env:
  LINKERD_VERSION: edge-21.5.2
  LINKERD_INIT_VERSION: v1.3.12
  K3D_VERSION: v4.4.4
  KUBECTL_VERSION: v1.21.1
  PROXY_IMAGE: linkerd-ci/linkerd/proxy

jobs:
  k3d-test:
    name: K3d Tests
    permissions:
      contents: read
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - run: mkdir -p ./target/bin

      - name: Fetch kubectl ${{ env.KUBECTL_VERSION }}
        run: |
          # Fetch kubectl
          curl -vsL --retry 2 \
            --output ./target/bin/kubectl \
            "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod 755 ./target/bin/kubectl

      - name: Fetch k3d ${{ env.K3D_VERSION }}
        run: |
          # Fetch k3d
          curl -vsL --retry 2 \
            --output ./target/bin/k3d \
            "https://github.com/rancher/k3d/releases/download/${K3D_VERSION}/k3d-linux-amd64"
          chmod 755 ./target/bin/k3d

      - name: Create cluster
        run: |
          ./target/bin/k3d cluster create
          ./target/bin/kubectl cluster-info
          ./target/bin/kubectl version

      # If we let k3d fetch the images, it can take 5+ minutes for the containers to start, so
      # instead we parallelize fetching the needed control plane images and pre-load them into the
      # cluster so that container start promptly.
      - name: Fetch linkerd ${{ env.LINKERD_VERSION }}
        run: |
          # Install Linkerd CLI
          curl -vsL --retry 2 \
            --output ./target/bin/linkerd \
            "https://github.com/linkerd/linkerd2/releases/download/${LINKERD_VERSION}/linkerd2-cli-${LINKERD_VERSION}-linux-amd64"
          chmod 755 ./target/bin/linkerd

          docker pull -q ghcr.io/linkerd/controller:${LINKERD_VERSION} &
          docker pull -q ghcr.io/linkerd/proxy:${LINKERD_VERSION} &
          docker pull -q ghcr.io/linkerd/proxy-init:${LINKERD_INIT_VERSION} &
          wait %1 %2 %3
          ./target/bin/k3d image import \
              ghcr.io/linkerd/controller:${LINKERD_VERSION} \
              ghcr.io/linkerd/proxy:${LINKERD_VERSION} \
              ghcr.io/linkerd/proxy-init:${LINKERD_INIT_VERSION}

      - name: Install linkerd control plane
        run: |
          # Ensure the cluster is ready for Linkerd.
          ./target/bin/linkerd check --pre

          # Install only the core Linkerd control-plane using the previously loaded images.
          ./target/bin/linkerd install \
                --set controllerImage=ghcr.io/linkerd/controller \
                --set proxyImage=ghcr.io/linkerd/proxy \
                --set proxyInitImage=ghcr.io/linkerd/proxy-init \
              | ./target/bin/kubectl apply -f -

          # Wait for the control plane to become ready for up to 10 minutes.
          for i in $(seq 1 10); do
            if ./target/bin/linkerd check --wait=1m ; then
              exit 0
            fi
            ./target/bin/kubectl get po -n linkerd
          done
          exit 1

      # Build a docker image for the working proxy, based on a recent Linkerd version for its
      # runtime image.
      - name: Build proxy
        run: |
          export RUNTIME_IMAGE="ghcr.io/linkerd/proxy:${LINKERD_VERSION}"
          export DOCKER_TAG="${PROXY_IMAGE}:${GITHUB_SHA}"
          export DOCKER_UNOPTIMIZED=1
          make docker
          ./target/bin/k3d image import "${DOCKER_TAG}"

      - name: Run tests
        run: |
          exit 1 # TODO
