name: Kubernetes

on:
  pull_request: {}
  push:
    branches:
      - "ver/k3d-tests"

# Don't bother with release builds, which take quite a bit longer
env:
  DOCKER_UNOPTIMIZED: "1"
  LINKERD_VERSION: edge-21.5.2
  K3D_VERSION: v4.4.4
  KUBECTL_VERSION: v1.21.1

jobs:
  k3d-test:
    name: K3d Tests
    permissions:
      contents: read
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Docker
        run:
          # Build a docker image for the working proxy, based on a recent Linkerd version for its
          # runtime image.
          export DOCKER_TAG="linkerd-ci/linkerd/proxy:${GITHUB_SHA}"
          export RUNTIME_IMAGE="ghcr.io/linkerd/proxy:${LINKERD_VERSION}"
          make docker

      - name: Install tools
        run:
          curl -sLo ./kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod 755 ./kubectl
          curl -sLo ./k3d "https://github.com/rancher/k3d/releases/download/${K3D_VERSION}/k3d-linux-amd64"
          chmod 755 ./k3d
          curl -sLo ./linkerd "https://github.com/linkerd/linkerd2/releases/download/${LINKERD_VERSION}/linkerd2-cli-${LINKERD_VERSION}-linux-amd64"
          chmod 755 ./linkerd

      - name: Setup cluster
        run:
          ./k3d cluster create
          ./k3d image import linkerd-ci/linkerd/proxy:${GITHUB_SHA}
          ./linkerd check --pre
          ./linkerd install \
            --set controllerImage=ghcr.io/linkerd/controller \
            --set proxyImage=ghcr.io/linkerd/proxy \
            --set proxyInitImage=ghcr.io/linkerd/proxy-init \
              | ./kubectl apply -f -
          ./linkerd check

      - name: Run tests
        run:
          kubectl get po -A
